# Generated by Django 4.2.6 on 2023-10-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('DNI', models.CharField(max_length=10)),
                ('departamento', models.CharField(max_length=255)),
                ('provincia', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Activo')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Activo')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('localidad', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Activo')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.CharField(max_length=10)),
                ('cargo', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
            ],
        ),
    ]
